/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arcanoid;

import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patryk
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    String level = "";
    String colorPaddle = "";
    
    public Settings() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        saveBT = new javax.swing.JButton();
        easyRB = new javax.swing.JRadioButton();
        mediumRB = new javax.swing.JRadioButton();
        hardRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blueRB = new javax.swing.JRadioButton();
        redRB = new javax.swing.JRadioButton();
        greenRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arcanoid");

        jPanel1.setLayout(null);

        saveBT.setBackground(new java.awt.Color(255, 51, 51));
        saveBT.setText("Save and close");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });
        jPanel1.add(saveBT);
        saveBT.setBounds(70, 310, 130, 60);

        easyRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(easyRB);
        easyRB.setForeground(new java.awt.Color(255, 51, 51));
        easyRB.setSelected(true);
        easyRB.setText("Easy");
        jPanel1.add(easyRB);
        easyRB.setBounds(50, 170, 70, 21);

        mediumRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(mediumRB);
        mediumRB.setForeground(new java.awt.Color(255, 51, 51));
        mediumRB.setText("Medium");
        jPanel1.add(mediumRB);
        mediumRB.setBounds(50, 210, 80, 21);

        hardRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(hardRB);
        hardRB.setForeground(new java.awt.Color(255, 51, 51));
        hardRB.setText("Hard");
        jPanel1.add(hardRB);
        hardRB.setBounds(50, 250, 60, 21);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Difficulty level:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 130, 90, 25);

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Paddle color:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 130, 80, 25);

        blueRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(blueRB);
        blueRB.setForeground(new java.awt.Color(51, 51, 255));
        blueRB.setSelected(true);
        blueRB.setText("Blue");
        jPanel1.add(blueRB);
        blueRB.setBounds(160, 170, 68, 21);

        redRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(redRB);
        redRB.setForeground(new java.awt.Color(255, 51, 51));
        redRB.setText("Red");
        jPanel1.add(redRB);
        redRB.setBounds(160, 210, 55, 21);

        greenRB.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(greenRB);
        greenRB.setForeground(new java.awt.Color(51, 204, 0));
        greenRB.setText("Green");
        jPanel1.add(greenRB);
        greenRB.setBounds(160, 250, 70, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/settings.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-2, -3, 300, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        FileWriter myWriter;
        try {
            myWriter = new FileWriter("difficulty.txt");
            if(easyRB.isSelected())
            {
            myWriter.write("easy");
            }else if(mediumRB.isSelected()){
            myWriter.write("medium");
            }else if(hardRB.isSelected()){
            myWriter.write("hard");
            }
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            myWriter = new FileWriter("paddlecolor.txt");
            if(blueRB.isSelected())
            {
            myWriter.write("blue");
            }else if(redRB.isSelected()){
            myWriter.write("red");
            }else if(greenRB.isSelected()){
            myWriter.write("green");
            }
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        Game gameFrame = new Game();
        gameFrame.setVisible(true);
        this.dispose();
    }

    public void set(){
        File myObj;
        try{
        myObj = new File("difficulty.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                level = myReader.nextLine();
            }
            myReader.close();
        }catch(IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
        myObj = new File("paddlecolor.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                colorPaddle = myReader.nextLine();
            }
            myReader.close();
        }catch(IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch(level){
            case "easy": easyRB.setSelected(true);break;
            case "medium": mediumRB.setSelected(true);break;
            case "hard": hardRB.setSelected(true);break;
            default: {
            easyRB.setSelected(true);break;
            }
        }
        switch(colorPaddle){
            case "blue": blueRB.setSelected(true);break;
            case "red": redRB.setSelected(true);break;
            case "green": greenRB.setSelected(true);break;
        }
    }
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton easyRB;
    private javax.swing.JRadioButton greenRB;
    private javax.swing.JRadioButton hardRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mediumRB;
    private javax.swing.JRadioButton redRB;
    private javax.swing.JButton saveBT;
    // End of variables declaration//GEN-END:variables
}
