/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zetcode;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patryk
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    String level = "";
    String color = "";
    public Settings() {
        initComponents();
        set();
        
        /*
        switch(level){
            case "easy": easyRB.isSelected();break;
            case "medium": mediumRB.isSelected();break;
            case "hard": hardRB.isSelected();break;
            default: {
            easyRB.isSelected();break;
            }
        }
        switch(color){
            case "blue": blueRB.isSelected();break;
            case "red": redRB.isSelected();break;
            case "green": greenRB.isSelected();break;
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        saveBT = new javax.swing.JButton();
        easyRB = new javax.swing.JRadioButton();
        mediumRB = new javax.swing.JRadioButton();
        hardRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blueRB = new javax.swing.JRadioButton();
        redRB = new javax.swing.JRadioButton();
        greenRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saveBT.setText("Save and close");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });

        buttonGroup1.add(easyRB);
        easyRB.setSelected(true);
        easyRB.setText("Easy");

        buttonGroup1.add(mediumRB);
        mediumRB.setText("Medium");

        buttonGroup1.add(hardRB);
        hardRB.setText("Hard");

        jLabel1.setText("Difficulty level:");

        jLabel2.setText("Paddle color:");

        buttonGroup2.add(blueRB);
        blueRB.setSelected(true);
        blueRB.setText("Blue");

        buttonGroup2.add(redRB);
        redRB.setText("Red");

        buttonGroup2.add(greenRB);
        greenRB.setText("Green");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(saveBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(easyRB)
                            .addComponent(mediumRB)
                            .addComponent(hardRB))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueRB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redRB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenRB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(easyRB)
                    .addComponent(blueRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediumRB)
                    .addComponent(redRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hardRB)
                    .addComponent(greenRB))
                .addGap(49, 49, 49)
                .addComponent(saveBT)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        FileWriter myWriter;
        try {
            myWriter = new FileWriter("difficulty.txt");
            if(easyRB.isSelected())
            {
            myWriter.write("easy");
            }else if(mediumRB.isSelected()){
            myWriter.write("medium");
            }else if(hardRB.isSelected()){
            myWriter.write("hard");
            }
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            myWriter = new FileWriter("paddlecolor.txt");
            if(blueRB.isSelected())
            {
            myWriter.write("blue");
            }else if(redRB.isSelected()){
            myWriter.write("red");
            }else if(greenRB.isSelected()){
            myWriter.write("green");
            }
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        Game gameFrame = new Game();
        gameFrame.setVisible(true);
        //close this frame
        this.dispose();
    }//GEN-LAST:event_saveBTActionPerformed

    public void set(){
        File myObj;
        try{
        myObj = new File("difficulty.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                level = myReader.nextLine();
            }
            myReader.close();
        }catch(IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
        myObj = new File("paddlecolor.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                color = myReader.nextLine();
            }
            myReader.close();
        }catch(IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch(level){
            case "easy": easyRB.setSelected(true);break;
            case "medium": mediumRB.setSelected(true);break;
            case "hard": hardRB.setSelected(true);break;
            default: {
            easyRB.setSelected(true);break;
            }
        }
        switch(color){
            case "blue": blueRB.setSelected(true);break;
            case "red": redRB.setSelected(true);break;
            case "green": greenRB.setSelected(true);break;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton easyRB;
    private javax.swing.JRadioButton greenRB;
    private javax.swing.JRadioButton hardRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton mediumRB;
    private javax.swing.JRadioButton redRB;
    private javax.swing.JButton saveBT;
    // End of variables declaration//GEN-END:variables
}
